sudo: false
language: node_js
node_js:  
  - node
script:
  - npm test
  - npm coverage

after_success:
- npm run coverage
- npm run coveralls
- istanbul cover ./node_modules/mocha/bin/_mocha --no-default-excludes --report lcovonly -- -R spec | ./node_modules/coveralls/bin/coveralls.js
