sudo: false
language: node_js
node_js:  
  - node
install: npm install
script:
  - npm run test

after_success: 
  - npm run coveralls
  - npm run coveralls_v2
after_failure: 
  - npm run coveralls
  - npm run coveralls_v2